/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Input */
        get: operations["project_input_api_v1_projects__project_id__input_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_v1_projects__project_id__revisions_get"];
        put?: never;
        /** Revise */
        post: operations["revise_api_v1_projects__project_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/revisions/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision Compare */
        get: operations["revision_compare_api_v1_projects__project_id__revisions_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Import */
        post: operations["preview_import_api_v1_projects__project_id__imports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/imports/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_api_v1_projects__project_id__imports_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Page */
        get: operations["run_page_api_v1_runs_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_v1_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actual */
        Actual: {
            /** Id */
            id: string;
            /** Phase Id */
            phase_id: string;
            /** Month */
            month: string;
            /**
             * Known On
             * Format: date
             */
            known_on: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "sales" | "collections" | "revenue" | "cogs" | "development" | "payments" | "expenses" | "expense_payments" | "taxes" | "tax_payments" | "interest" | "borrowing" | "repayment";
            /** Amount */
            amount: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Contract Id */
            contract_id?: string | null;
        };
        /** Assumptions */
        Assumptions: {
            /**
             * Opening Month
             * @default 2026-01
             */
            opening_month: string;
            /**
             * Opening Cash
             * @default 0
             */
            opening_cash: string;
            /**
             * Monthly Overhead
             * @default 50000
             */
            monthly_overhead: string;
            /**
             * Marketing Rate
             * @default 0.02
             */
            marketing_rate: string;
            /**
             * Tax Rate
             * @default 0.03
             */
            tax_rate: string;
            /**
             * Down Payment Rate
             * @default 0.30
             */
            down_payment_rate: string;
            /**
             * Collection Lag
             * @default 3
             */
            collection_lag: number;
            /**
             * Expense Payment Lag
             * @default 0
             */
            expense_payment_lag: number;
            /**
             * Loan Limit
             * @default 20000000
             */
            loan_limit: string;
            /**
             * Annual Interest Rate
             * @default 0.05
             */
            annual_interest_rate: string;
            /** Loan Draws */
            loan_draws?: components["schemas"]["Payment"][];
            /** Loan Repayments */
            loan_repayments?: components["schemas"]["Payment"][];
        };
        /** Body_preview_import_api_v1_projects__project_id__imports_preview_post */
        Body_preview_import_api_v1_projects__project_id__imports_preview_post: {
            /** File */
            file: string;
        };
        /** Comparison */
        Comparison: {
            /** Left Id */
            left_id: string;
            /** Right Id */
            right_id: string;
            /** Months */
            months: string[];
            /** Profit Deltas */
            profit_deltas: string[];
            /** Membership Changed */
            membership_changed: boolean;
            /** Bridge */
            bridge?: components["schemas"]["ProfitBridge"][];
            total_bridge?: components["schemas"]["ProfitBridge"] | null;
        };
        /** Contract */
        Contract: {
            /** Id */
            id: string;
            /** Phase Id */
            phase_id: string;
            /** Sale Month */
            sale_month: string;
            /** Area */
            area: string;
            /** Amount */
            amount: string;
            /**
             * Known On
             * Format: date
             */
            known_on: string;
            /** Recognized Month */
            recognized_month?: string | null;
            /** Collections */
            collections?: components["schemas"]["Payment"][];
        };
        /** Cost */
        Cost: {
            /** Id */
            id: string;
            /** Phase Id */
            phase_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "land" | "construction" | "other";
            /** Amount */
            amount: string;
            /** Incurred Month */
            incurred_month: string;
            /**
             * Known On
             * Format: date
             */
            known_on: string;
            /** Payments */
            payments?: components["schemas"]["Payment"][];
        };
        /** Dataset */
        Dataset: {
            /** Phases */
            phases?: components["schemas"]["Phase"][];
            /** Contracts */
            contracts?: components["schemas"]["Contract"][];
            /** Costs */
            costs?: components["schemas"]["Cost"][];
            /** Actuals */
            actuals?: components["schemas"]["Actual"][];
            assumptions?: components["schemas"]["Assumptions"];
            /**
             * Actual Closed Through
             * @default 2026-08
             */
            actual_closed_through: string;
        };
        /** Evidence */
        Evidence: {
            /** Run Id */
            run_id: string;
            /** Metric */
            metric: string;
            /** Month */
            month: string | null;
            /** Revision Ids */
            revision_ids: string[];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Members */
            members: components["schemas"]["Member"][];
        };
        /** FieldChange */
        FieldChange: {
            /** Path */
            path: string;
            /** Before */
            before: string | null;
            /** After */
            after: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "changed";
        };
        /** ForecastResult */
        ForecastResult: {
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /**
             * Unit
             * @default 元
             */
            unit: string;
            /**
             * Profit Basis
             * @default 模拟管理口径利润
             */
            profit_basis: string;
            /**
             * Rule Version
             * @default demo-1
             */
            rule_version: string;
            /** Target Months */
            target_months: string[];
            /** Months */
            months: components["schemas"]["MonthResult"][];
            summary: components["schemas"]["Summary"];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Warnings */
            warnings: string[];
            /** Sensitivity */
            sensitivity?: components["schemas"]["Sensitivity"][];
            /** Scenario Totals */
            scenario_totals?: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportConfirm */
        ImportConfirm: {
            /** Base Version */
            base_version: number;
            /**
             * Known On
             * Format: date
             */
            known_on: string;
            /** Records */
            records: components["schemas"]["Actual"][];
        };
        /** ImportPreview */
        ImportPreview: {
            /** Project Id */
            project_id: string;
            /** Base Version */
            base_version: number;
            /** Additions */
            additions: components["schemas"]["Actual"][];
            /** Duplicates */
            duplicates: string[];
            /** Errors */
            errors: string[];
        };
        /** Member */
        Member: {
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Run Id */
            run_id: string;
            /** Revision Id */
            revision_id: string;
            /** Status */
            status: string;
            /** Profit */
            profit?: string | null;
            /** Error */
            error?: string | null;
        };
        /** MonthResult */
        MonthResult: {
            /** Month */
            month: string;
            /**
             * Period
             * @enum {string}
             */
            period: "actual" | "estimate" | "forecast" | "mixed";
            /**
             * Sales
             * @default 0.00
             */
            sales: string;
            /**
             * Collections
             * @default 0.00
             */
            collections: string;
            /**
             * Revenue
             * @default 0.00
             */
            revenue: string;
            /**
             * Cogs
             * @default 0.00
             */
            cogs: string;
            /**
             * Development
             * @default 0.00
             */
            development: string;
            /**
             * Payments
             * @default 0.00
             */
            payments: string;
            /**
             * Expenses
             * @default 0.00
             */
            expenses: string;
            /**
             * Expense Payments
             * @default 0.00
             */
            expense_payments: string;
            /**
             * Taxes
             * @default 0.00
             */
            taxes: string;
            /**
             * Tax Payments
             * @default 0.00
             */
            tax_payments: string;
            /**
             * Interest
             * @default 0.00
             */
            interest: string;
            /**
             * Borrowing
             * @default 0.00
             */
            borrowing: string;
            /**
             * Repayment
             * @default 0.00
             */
            repayment: string;
            /**
             * Profit
             * @default 0.00
             */
            profit: string;
            /**
             * Cumulative Profit
             * @default 0.00
             */
            cumulative_profit: string;
            /**
             * Net Cash Flow
             * @default 0.00
             */
            net_cash_flow: string;
            /**
             * Cash Balance
             * @default 0.00
             */
            cash_balance: string;
            /**
             * Uncovered Gap
             * @default 0.00
             */
            uncovered_gap: string;
        };
        /** Overrides */
        Overrides: {
            /**
             * Price Change
             * @default 0
             */
            price_change: string;
            /**
             * Remaining Cost Change
             * @default 0
             */
            remaining_cost_change: string;
            /**
             * Collection Delay
             * @default 0
             */
            collection_delay: number;
            /** Delivery Delays */
            delivery_delays?: {
                [key: string]: number;
            };
        };
        /** Payment */
        Payment: {
            /** Month */
            month: string;
            /** Amount */
            amount: string;
        };
        /** Phase */
        Phase: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Area */
            area: string;
            /** Price */
            price: string;
            /** Sales Start */
            sales_start: string;
            /**
             * Sales Months
             * @default 6
             */
            sales_months: number;
            /** Delivery Month */
            delivery_month: string;
            /**
             * Known On
             * Format: date
             * @default 2026-01-01
             */
            known_on: string;
        };
        /** ProfitBridge */
        ProfitBridge: {
            /** Month */
            month: string;
            /** Revenue */
            revenue: string;
            /** Cogs */
            cogs: string;
            /** Expenses */
            expenses: string;
            /** Taxes */
            taxes: string;
            /** Interest */
            interest: string;
            /** Profit */
            profit: string;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Archived */
            archived: boolean;
            /** Version */
            version: number;
            /** Revision Id */
            revision_id: string;
            /** Created At */
            created_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Template
             * @default blank
             * @enum {string}
             */
            template: "blank" | "demo";
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Name */
            name: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Base Version */
            base_version: number;
        };
        /** Revision */
        Revision: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Version */
            version: number;
            /** Known On */
            known_on: string;
            /** Created At */
            created_at: string;
            /** Note */
            note: string;
            data: components["schemas"]["Dataset"];
        };
        /** RevisionComparison */
        RevisionComparison: {
            /** Project Id */
            project_id: string;
            /** Left Id */
            left_id: string;
            /** Right Id */
            right_id: string;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /** RevisionInfo */
        RevisionInfo: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Version */
            version: number;
            /** Known On */
            known_on: string;
            /** Created At */
            created_at: string;
            /** Note */
            note: string;
        };
        /** RevisionPage */
        RevisionPage: {
            /** Items */
            items: components["schemas"]["RevisionInfo"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** RevisionWrite */
        RevisionWrite: {
            /** Base Version */
            base_version: number;
            /**
             * Known On
             * Format: date
             */
            known_on: string;
            /**
             * Note
             * @default 手动修订
             */
            note: string;
            data: components["schemas"]["Dataset"];
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "portfolio";
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Forecast Origin */
            forecast_origin: string;
            /** Information Cutoff */
            information_cutoff: string;
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "base" | "optimistic" | "prudent";
            /** Project Ids */
            project_ids: string[];
            /** Project Names */
            project_names: string[];
            /** Revision Ids */
            revision_ids: string[];
            /** Error */
            error?: string | null;
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Parent Id */
            parent_id?: string | null;
            /** Supersedes Run Id */
            supersedes_run_id?: string | null;
            result?: components["schemas"]["ForecastResult"] | null;
            /** Members */
            members?: components["schemas"]["Member"][];
            /** Steps */
            steps?: components["schemas"]["Step"][];
            /** Overrides */
            overrides?: {
                [key: string]: components["schemas"]["Overrides"];
            };
        };
        /** RunCreate */
        RunCreate: {
            /** Supersedes Run Id */
            supersedes_run_id?: string | null;
            /** Project Ids */
            project_ids: string[];
            /**
             * Kind
             * @default project
             * @enum {string}
             */
            kind: "project" | "portfolio";
            /**
             * Forecast Origin
             * Format: date
             * @default 2026-08-31
             */
            forecast_origin: string;
            /**
             * Information Cutoff
             * Format: date
             * @default 2026-08-31
             */
            information_cutoff: string;
            /**
             * Scenario
             * @default base
             * @enum {string}
             */
            scenario: "base" | "optimistic" | "prudent";
            /** Overrides */
            overrides?: {
                [key: string]: components["schemas"]["Overrides"];
            };
            /** Base Versions */
            base_versions?: {
                [key: string]: number;
            };
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Sensitivity */
        Sensitivity: {
            /** Label */
            label: string;
            /** Profit */
            profit?: string | null;
            /** Delta */
            delta?: string | null;
            /** Max Funding Gap */
            max_funding_gap?: string | null;
            /** Funding Gap Delta */
            funding_gap_delta?: string | null;
            /** Error */
            error?: string | null;
        };
        /** Source */
        Source: {
            /** Record Id */
            record_id: string;
            /**
             * Phase Id
             * @default
             */
            phase_id: string;
            /** Month */
            month: string;
            /** Metric */
            metric: string;
            /** Amount */
            amount: string;
            /** Rule */
            rule: string;
            /** Description */
            description: string;
        };
        /** Step */
        Step: {
            /** Sequence */
            sequence: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Created At */
            created_at: string;
            /** Attempt */
            attempt: number;
        };
        /** Summary */
        Summary: {
            /** Next Month Profit */
            next_month_profit: string;
            /** Twelve Month Profit */
            twelve_month_profit: string;
            /** Lifecycle Profit */
            lifecycle_profit: string;
            /** Max Funding Gap */
            max_funding_gap: string;
            /** Ending Debt */
            ending_debt: string;
            /** Ending Receivables */
            ending_receivables: string;
            /** Range Low */
            range_low: string;
            /** Range High */
            range_high: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_input_api_v1_projects__project_id__input_get: {
        parameters: {
            query?: {
                revision_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_api_v1_projects__project_id__revisions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_api_v1_projects__project_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revision_compare_api_v1_projects__project_id__revisions_compare_get: {
        parameters: {
            query: {
                left_id: string;
                right_id: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_v1_projects__project_id__imports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_api_v1_projects__project_id__imports_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_api_v1_projects__project_id__imports_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                scope_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_page_api_v1_runs_page_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                kind?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_compare_get: {
        parameters: {
            query: {
                left_id: string;
                right_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_v1_runs__run_id__evidence_get: {
        parameters: {
            query?: {
                metric?: string;
                month?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
